"""FastAPI app generated by intpot."""

from fastapi import FastAPI, Body

import json

app = FastAPI()



@app.post("/create")
def create(
    title: str = Body(..., description="Task title"),
    priority: int = Body(default=3, description="Priority level 1-5"),
    tags: str = Body(default='', description="Comma-separated tags"),
) -> dict:
    """Create a new task with optional priority and tags."""

    tag_list = [t.strip() for t in tags.split(',') if t.strip()]
    task = {'title': title, 'priority': priority, 'tags': tag_list}
    return json.dumps(task, indent=2)


@app.post("/search")
def search(
    query: str = Body(..., description="Search query"),
    limit: int = Body(default=10, description="Max results to return"),
    include_done: bool = Body(default=False, description="Include completed tasks"),
) -> dict:
    """Search tasks by title or tag."""

    results = [{'title': f'Match: {query}', 'done': False}, {'title': f'Another: {query}', 'done': True}]
    if not include_done:
        results = [r for r in results if not r['done']]
    return json.dumps(results[:limit], indent=2)


@app.post("/stats")
def stats() -> dict:
    """Show task statistics."""

    summary = {'total': 42, 'done': 15, 'pending': 27}
    return json.dumps(summary)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

