"""MCP server generated by intpot."""

from fastmcp import FastMCP

import json

mcp = FastMCP("generated-server")



@mcp.tool()
def create(
    title: str,
    priority: int = 3,
    tags: str = '',
) -> str:
    """Create a new task with optional priority and tags."""

    tag_list = [t.strip() for t in tags.split(',') if t.strip()]
    task = {'title': title, 'priority': priority, 'tags': tag_list}
    return json.dumps(task, indent=2)


@mcp.tool()
def search(
    query: str,
    limit: int = 10,
    include_done: bool = False,
) -> str:
    """Search tasks by title or tag."""

    results = [{'title': f'Match: {query}', 'done': False}, {'title': f'Another: {query}', 'done': True}]
    if not include_done:
        results = [r for r in results if not r['done']]
    return json.dumps(results[:limit], indent=2)


@mcp.tool()
def stats(
) -> str:
    """Show task statistics."""

    summary = {'total': 42, 'done': 15, 'pending': 27}
    return json.dumps(summary)


if __name__ == "__main__":
    mcp.run()

