"""MCP server generated by intpot."""

from fastmcp import FastMCP

import json

mcp = FastMCP('advanced_api')


@mcp.tool()
def create_user(
    username: str,
    email: str,
    role: str = 'member',
) -> dict:
    """Create a new user account."""

    return {"username": username, "email": email, "role": role, "created": True}


@mcp.tool()
def get_user(
    user_id: str,
) -> dict:
    """Retrieve a user by their ID."""

    return {"user_id": user_id, "username": "example", "role": "member"}


@mcp.tool()
def update_user(
    user_id: str,
    email: str | None = None,
    role: str | None = None,
) -> dict:
    """Update user fields."""

    changes = {}
    if email is not None:
        changes["email"] = email
    if role is not None:
        changes["role"] = role
    return {"user_id": user_id, "updated": changes}


@mcp.tool()
def delete_user(
    user_id: str,
) -> dict:
    """Delete a user by their ID."""

    return {"user_id": user_id, "deleted": True}


@mcp.tool()
def list_users(
    limit: int = 20,
    offset: int = 0,
) -> dict:
    """List users with pagination."""

    return {"users": [], "limit": limit, "offset": offset, "total": 0}


@mcp.tool()
def bulk_create(
    payload: str,
) -> dict:
    """Create multiple users from a JSON payload."""

    users = json.loads(payload)
    return {"created": len(users), "users": users}


if __name__ == "__main__":
    mcp.run()
