"""CLI app generated by intpot."""

from typing import Optional
import typer

import json

app = typer.Typer()


def _create_user_impl(
    username: str,
    email: str,
    role: str,
) -> None:
    """Create a new user account."""
    typer.echo({'username': username, 'email': email, 'role': role, 'created': True})


# NOTE: Original used dependency injection: get_db
@app.command()
def create_user(
    username: str = typer.Argument(..., help="Unique username"),
    email: str = typer.Argument(..., help="Email address"),
    role: str = typer.Option('member', help="User role"),
) -> None:
    """Create a new user account."""
    result = _create_user_impl(username, email, role)
    if result is not None:
        typer.echo(result)


def _get_user_impl(
    user_id: str,
) -> None:
    """Retrieve a user by their ID."""
    typer.echo({'user_id': user_id, 'username': 'example', 'role': 'member'})


# NOTE: Original used dependency injection: get_db
@app.command()
def get_user(
    user_id: str = typer.Argument(..., help="Path parameter from /users/{user_id}"),
) -> None:
    """Retrieve a user by their ID."""
    result = _get_user_impl(user_id)
    if result is not None:
        typer.echo(result)


def _update_user_impl(
    user_id: str,
    email: Optional[str],
    role: Optional[str],
) -> None:
    """Update user fields."""
    changes = {}
    if email is not None:
        changes['email'] = email
    if role is not None:
        changes['role'] = role
    typer.echo({'user_id': user_id, 'updated': changes})


# NOTE: Original used dependency injection: get_db
@app.command()
def update_user(
    user_id: str = typer.Argument(..., help="Path parameter from /users/{user_id}"),
    email: Optional[str] = typer.Option(None, help="New email address"),
    role: Optional[str] = typer.Option(None, help="New role"),
) -> None:
    """Update user fields."""
    result = _update_user_impl(user_id, email, role)
    if result is not None:
        typer.echo(result)


def _delete_user_impl(
    user_id: str,
) -> None:
    """Delete a user by their ID."""
    typer.echo({'user_id': user_id, 'deleted': True})


# NOTE: Original used dependency injection: get_db
@app.command()
def delete_user(
    user_id: str = typer.Argument(..., help="Path parameter from /users/{user_id}"),
) -> None:
    """Delete a user by their ID."""
    result = _delete_user_impl(user_id)
    if result is not None:
        typer.echo(result)


def _list_users_impl(
    limit: int,
    offset: int,
) -> None:
    """List users with pagination."""
    typer.echo({'users': [], 'limit': limit, 'offset': offset, 'total': 0})


# NOTE: Original used dependency injection: get_db
@app.command()
def list_users(
    limit: int = typer.Option(20, help=""),
    offset: int = typer.Option(0, help=""),
) -> None:
    """List users with pagination."""
    result = _list_users_impl(limit, offset)
    if result is not None:
        typer.echo(result)


def _bulk_create_impl(
    payload: str,
) -> None:
    """Create multiple users from a JSON payload."""
    users = json.loads(payload)
    typer.echo({'created': len(users), 'users': users})


# NOTE: Original used dependency injection: get_db
@app.command()
def bulk_create(
    payload: str = typer.Argument(..., help="JSON array of user objects"),
) -> None:
    """Create multiple users from a JSON payload."""
    result = _bulk_create_impl(payload)
    if result is not None:
        typer.echo(result)


if __name__ == "__main__":
    app()

