"""CLI app generated by intpot."""
from __future__ import annotations


from fastapi import status
import json

from typing import Optional
import typer as _intpot_cli_typer

app = _intpot_cli_typer.Typer(name='advanced_api')


def _create_user_impl(
    username: str,
    email: str,
    role: str,
) -> dict:
    """Create a new user account."""
    return {
        "username": username,
        "email": email,
        "role": role,
        "created": True,
        "status": status.HTTP_201_CREATED,
    }


@app.command()
def create_user(
    username: str = _intpot_cli_typer.Argument(..., help='Unique username'),
    email: str = _intpot_cli_typer.Argument(..., help='Email address'),
    role: str = _intpot_cli_typer.Option('member', help='User role'),
) -> None:
    """Create a new user account."""
    result = _create_user_impl(username, email, role)
    if result is not None:
        _intpot_cli_typer.echo(result)


def _get_user_impl(
    user_id: str,
) -> dict:
    """Retrieve a user by their ID."""
    if user_id:
        return {"user_id": user_id, "username": "example", "role": "member"}
    raise ValueError("user_id is required")


@app.command()
def get_user(
    user_id: str = _intpot_cli_typer.Argument(..., help='Path parameter from /users/{user_id}'),
) -> None:
    """Retrieve a user by their ID."""
    result = _get_user_impl(user_id)
    if result is not None:
        _intpot_cli_typer.echo(result)


def _update_user_impl(
    user_id: str,
    email: Optional[str],
    role: Optional[str],
) -> dict:
    """Update user fields."""
    changes = {}
    if email is not None:
        changes["email"] = email
    if role is not None:
        changes["role"] = role
    return {"user_id": user_id, "updated": changes}


@app.command()
def update_user(
    user_id: str = _intpot_cli_typer.Argument(..., help='Path parameter from /users/{user_id}'),
    email: Optional[str] = _intpot_cli_typer.Option(None, help='New email address'),
    role: Optional[str] = _intpot_cli_typer.Option(None, help='New role'),
) -> None:
    """Update user fields."""
    result = _update_user_impl(user_id, email, role)
    if result is not None:
        _intpot_cli_typer.echo(result)


def _delete_user_impl(
    user_id: str,
) -> dict:
    """Delete a user by their ID."""
    return {"user_id": user_id, "deleted": True}


@app.command()
def delete_user(
    user_id: str = _intpot_cli_typer.Argument(..., help='Path parameter from /users/{user_id}'),
) -> None:
    """Delete a user by their ID."""
    result = _delete_user_impl(user_id)
    if result is not None:
        _intpot_cli_typer.echo(result)


def _list_users_impl(
    limit: int,
    offset: int,
) -> dict:
    """List users with pagination."""
    return {"users": [], "limit": limit, "offset": offset, "total": 0}


@app.command()
def list_users(
    limit: int = _intpot_cli_typer.Option(20, help=''),
    offset: int = _intpot_cli_typer.Option(0, help=''),
) -> None:
    """List users with pagination."""
    result = _list_users_impl(limit, offset)
    if result is not None:
        _intpot_cli_typer.echo(result)


def _bulk_create_impl(
    payload: str,
) -> dict:
    """Create multiple users from a JSON payload."""
    users = json.loads(payload)
    return {"created": len(users), "users": users}


@app.command()
def bulk_create(
    payload: str = _intpot_cli_typer.Argument(..., help='JSON array of user objects'),
) -> None:
    """Create multiple users from a JSON payload."""
    result = _bulk_create_impl(payload)
    if result is not None:
        _intpot_cli_typer.echo(result)


if __name__ == "__main__":
    app()
