"""MCP server generated by intpot."""


from fastapi import status
import json

from typing import Optional
from fastmcp import FastMCP as _intpot_mcp_fastmcp

mcp = _intpot_mcp_fastmcp('advanced_api')
_intpot_required = object()


def _create_user_impl(
    username: str = _intpot_required,
    email: str = _intpot_required,
    role: str = 'member',
) -> dict:
    """Create a new user account."""
    if username is _intpot_required:
        raise TypeError('Missing required argument: username')
    if email is _intpot_required:
        raise TypeError('Missing required argument: email')
    return {
        "username": username,
        "email": email,
        "role": role,
        "created": True,
        "status": status.HTTP_201_CREATED,
    }


@mcp.tool(name='create_user')
def create_user(
    username: str,
    email: str,
    role: str = 'member',
) -> dict:
    """Create a new user account."""

    return _create_user_impl(username, email, role)

def _get_user_impl(
    user_id: str = _intpot_required,
) -> dict:
    """Retrieve a user by their ID."""
    if user_id is _intpot_required:
        raise TypeError('Missing required argument: user_id')
    if user_id:
        return {"user_id": user_id, "username": "example", "role": "member"}
    raise ValueError("user_id is required")


@mcp.tool(name='get_user')
def get_user(
    user_id: str,
) -> dict:
    """Retrieve a user by their ID."""

    return _get_user_impl(user_id)

def _update_user_impl(
    user_id: str = _intpot_required,
    email: Optional[str] = None,
    role: Optional[str] = None,
) -> dict:
    """Update user fields."""
    if user_id is _intpot_required:
        raise TypeError('Missing required argument: user_id')
    changes = {}
    if email is not None:
        changes["email"] = email
    if role is not None:
        changes["role"] = role
    return {"user_id": user_id, "updated": changes}


@mcp.tool(name='update_user')
def update_user(
    user_id: str,
    email: Optional[str] = None,
    role: Optional[str] = None,
) -> dict:
    """Update user fields."""

    return _update_user_impl(user_id, email, role)

def _delete_user_impl(
    user_id: str = _intpot_required,
) -> dict:
    """Delete a user by their ID."""
    if user_id is _intpot_required:
        raise TypeError('Missing required argument: user_id')
    return {"user_id": user_id, "deleted": True}


@mcp.tool(name='delete_user')
def delete_user(
    user_id: str,
) -> dict:
    """Delete a user by their ID."""

    return _delete_user_impl(user_id)

def _list_users_impl(
    limit: int = 20,
    offset: int = 0,
) -> dict:
    """List users with pagination."""
    return {"users": [], "limit": limit, "offset": offset, "total": 0}


@mcp.tool(name='list_users')
def list_users(
    limit: int = 20,
    offset: int = 0,
) -> dict:
    """List users with pagination."""

    return _list_users_impl(limit, offset)

def _bulk_create_impl(
    payload: str = _intpot_required,
) -> dict:
    """Create multiple users from a JSON payload."""
    if payload is _intpot_required:
        raise TypeError('Missing required argument: payload')
    users = json.loads(payload)
    return {"created": len(users), "users": users}


@mcp.tool(name='bulk_create')
def bulk_create(
    payload: str,
) -> dict:
    """Create multiple users from a JSON payload."""

    return _bulk_create_impl(payload)


if __name__ == "__main__":
    mcp.run()
