"""CLI app generated by intpot."""

import typer

from datetime import datetime
import hashlib
import json

app = typer.Typer()



@app.command()
def create_note(
    title: str = typer.Argument(..., help=""),
    body: str = typer.Argument(..., help=""),
    tags: str = typer.Option('', help=""),
) -> None:
    """Create a new note with a generated ID."""

    note_id = hashlib.md5(title.encode()).hexdigest()[:8]
    tag_list = [t.strip() for t in tags.split(',') if t.strip()]
    note = {'id': note_id, 'title': title, 'body': body, 'tags': tag_list, 'created': datetime.now().isoformat()}
    typer.echo(json.dumps(note, indent=2))


@app.command()
def search_notes(
    query: str = typer.Argument(..., help=""),
    max_results: int = typer.Option(5, help=""),
) -> None:
    """Search notes by keyword in title or body."""

    results = [{'id': 'abc123', 'title': f'Match: {query}', 'snippet': '...'}]
    typer.echo(json.dumps(results[:max_results]))


@app.command()
async def summarize(
    note_ids: str = typer.Argument(..., help=""),
) -> None:
    """Summarize multiple notes by their IDs (comma-separated)."""

    ids = [nid.strip() for nid in note_ids.split(',')]
    typer.echo(json.dumps({'summarized': len(ids), 'ids': ids}))


@app.command()
def export_all(
    format: str = typer.Option('json', help=""),
) -> None:
    """Export all notes in the specified format."""

    if format == 'json':
        typer.echo(json.dumps({'notes': [], 'count': 0}))
    typer.echo('No notes found.')


if __name__ == "__main__":
    app()

