"""FastAPI app generated by intpot."""

from fastapi import FastAPI, Body

from datetime import datetime
import hashlib
import json

app = FastAPI()



@app.post("/create_note")
def create_note(
    title: str = Body(...),
    body: str = Body(...),
    tags: str = Body(default=''),
) -> dict:
    """Create a new note with a generated ID."""

    note_id = hashlib.md5(title.encode()).hexdigest()[:8]
    tag_list = [t.strip() for t in tags.split(",") if t.strip()]
    note = {
        "id": note_id,
        "title": title,
        "body": body,
        "tags": tag_list,
        "created": datetime.now().isoformat(),
    }
    return json.dumps(note, indent=2)


@app.post("/search_notes")
def search_notes(
    query: str = Body(...),
    max_results: int = Body(default=5),
) -> dict:
    """Search notes by keyword in title or body."""

    results = [{"id": "abc123", "title": f"Match: {query}", "snippet": "..."}]
    return json.dumps(results[:max_results])


@app.post("/summarize")
async def summarize(
    note_ids: str = Body(...),
) -> dict:
    """Summarize multiple notes by their IDs (comma-separated)."""

    ids = [nid.strip() for nid in note_ids.split(",")]
    return json.dumps({"summarized": len(ids), "ids": ids})


@app.post("/export_all")
def export_all(
    format: str = Body(default='json'),
) -> dict:
    """Export all notes in the specified format."""

    if format == "json":
        return json.dumps({"notes": [], "count": 0})
    return "No notes found."


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

