"""FastAPI app generated by intpot."""


from datetime import datetime
import hashlib
import json

from fastapi import FastAPI as _intpot_fastapi_FastAPI, Body as _intpot_fastapi_Body

app = _intpot_fastapi_FastAPI(title='notes-server')


@app.post("/create_note")
def create_note(
    title: str = _intpot_fastapi_Body(...),
    body: str = _intpot_fastapi_Body(...),
    tags: str = _intpot_fastapi_Body(default=''),
) -> dict:
    """Create a new note with a generated ID."""

    note_id = hashlib.md5(title.encode()).hexdigest()[:8]
    tag_list = [t.strip() for t in tags.split(',') if t.strip()]
    note = {'id': note_id, 'title': title, 'body': body, 'tags': tag_list, 'created': datetime.now().isoformat()}
    return {'result': json.dumps(note, indent=2)}


@app.post("/search_notes")
def search_notes(
    query: str = _intpot_fastapi_Body(...),
    max_results: int = _intpot_fastapi_Body(default=5),
) -> dict:
    """Search notes by keyword in title or body."""

    results = [{'id': 'abc123', 'title': f'Match: {query}', 'snippet': '...'}]
    return {'result': json.dumps(results[:max_results])}


@app.post("/summarize")
async def summarize(
    note_ids: str = _intpot_fastapi_Body(...),
) -> dict:
    """Summarize multiple notes by their IDs (comma-separated)."""

    ids = [nid.strip() for nid in note_ids.split(',')]
    return {'result': json.dumps({'summarized': len(ids), 'ids': ids})}


@app.post("/export_all")
def export_all(
    format: str = _intpot_fastapi_Body(default='json'),
) -> dict:
    """Export all notes in the specified format."""

    if format == 'json':
        return {'result': json.dumps({'notes': [], 'count': 0})}
    return {'result': 'No notes found.'}


if __name__ == "__main__":
    import uvicorn

    # Loopback only. Change to "0.0.0.0" to expose this on the network.
    uvicorn.run(app, host="127.0.0.1", port=8000)
