"""MCP server generated by intpot."""

from fastmcp import FastMCP

mcp = FastMCP("generated-server")



@mcp.tool()
def add(
    a: int,
    b: int,
) -> dict:
    """Add two numbers together."""

    return {"result": a + b}


@mcp.tool()
def greet(
    name: str,
    greeting: str = 'Hello',
) -> dict:
    """Greet someone by name."""

    return {"message": f"{greeting}, {name}!"}


if __name__ == "__main__":
    mcp.run()

