# Conversion: API (FastAPI) → CLI (Typer)
# Source:     ../api_app.py
# Command:    intpot to cli examples/api_app.py
#
# Original input:
#
#   from fastapi import FastAPI
#   app = FastAPI()
#
#   @app.post("/add")
#   def add(a: int, b: int) -> dict:
#       """Add two numbers together."""
#       return {"result": a + b}
#
#   @app.post("/greet")
#   def greet(name: str, greeting: str = "Hello") -> dict:
#       """Greet someone by name."""
#       return {"message": f"{greeting}, {name}!"}
#
# Generated output below:
# ─────────────────────────────────────────

"""CLI app generated by intpot."""

import typer

app = typer.Typer()



@app.command()
def add(
    a: int = typer.Argument(..., help=""),
    b: int = typer.Argument(..., help=""),
) -> None:
    """Add two numbers together."""
    # TODO: implement
    typer.echo("add called")


@app.command()
def greet(
    name: str = typer.Argument(..., help=""),
    greeting: str = typer.Option('Hello', help=""),
) -> None:
    """Greet someone by name."""
    # TODO: implement
    typer.echo("greet called")


if __name__ == "__main__":
    app()
