"""CLI app generated by intpot."""
from __future__ import annotations


import typer as _intpot_cli_typer

app = _intpot_cli_typer.Typer(name='api_app')


def _add_impl(
    a: int,
    b: int,
) -> dict:
    """Add two numbers together."""
    return {"result": a + b}


@app.command()
def add(
    a: int = _intpot_cli_typer.Argument(..., help=''),
    b: int = _intpot_cli_typer.Argument(..., help=''),
) -> None:
    """Add two numbers together."""
    result = _add_impl(a, b)
    if result is not None:
        _intpot_cli_typer.echo(result)


def _greet_impl(
    name: str,
    greeting: str,
) -> dict:
    """Greet someone by name."""
    return {"message": f"{greeting}, {name}!"}


@app.command()
def greet(
    name: str = _intpot_cli_typer.Argument(..., help=''),
    greeting: str = _intpot_cli_typer.Option('Hello', help=''),
) -> None:
    """Greet someone by name."""
    result = _greet_impl(name, greeting)
    if result is not None:
        _intpot_cli_typer.echo(result)


if __name__ == "__main__":
    app()
