"""CLI app generated by intpot."""
from __future__ import annotations


import asyncio as _intpot_cli_asyncio
import inspect as _intpot_cli_inspect

import typer as _intpot_cli_typer

app = _intpot_cli_typer.Typer(name='api_app', help='api_app — powered by intpot')
_intpot_required = object()


def _add_impl(
    a: int = _intpot_required,
    b: int = _intpot_required,
) -> dict:
    """Add two numbers together."""
    if a is _intpot_required:
        raise TypeError('Missing required argument: a')
    if b is _intpot_required:
        raise TypeError('Missing required argument: b')
    return {'result': a + b}


@app.command(name='add')
def add(
    a: int = _intpot_cli_typer.Argument(..., help=''),
    b: int = _intpot_cli_typer.Argument(..., help=''),
) -> None:
    """Add two numbers together."""
    result = _add_impl(a, b)
    if _intpot_cli_inspect.iscoroutine(result):
        result = _intpot_cli_asyncio.run(result)
    if result is not None:
        _intpot_cli_typer.echo(result)


def _greet_impl(
    name: str = _intpot_required,
    greeting: str = 'Hello',
) -> dict:
    """Greet someone by name."""
    if name is _intpot_required:
        raise TypeError('Missing required argument: name')
    return {'message': f'{greeting}, {name}!'}


@app.command(name='greet')
def greet(
    name: str = _intpot_cli_typer.Argument(..., help=''),
    greeting: str = _intpot_cli_typer.Option('Hello', help=''),
) -> None:
    """Greet someone by name."""
    result = _greet_impl(name, greeting)
    if _intpot_cli_inspect.iscoroutine(result):
        result = _intpot_cli_asyncio.run(result)
    if result is not None:
        _intpot_cli_typer.echo(result)


if __name__ == "__main__":
    app()
