# Conversion: CLI (Typer) → API (FastAPI)
# Source:     ../cli_app.py
# Command:    intpot to api examples/cli_app.py
#
# Original input:
#
#   import typer
#   app = typer.Typer()
#
#   @app.command()
#   def add(
#       a: int = typer.Argument(..., help="First number"),
#       b: int = typer.Argument(..., help="Second number"),
#   ) -> None:
#       """Add two numbers together."""
#       typer.echo(a + b)
#
#   @app.command()
#   def greet(
#       name: str = typer.Argument(..., help="Name to greet"),
#       greeting: str = typer.Option("Hello", help="Greeting to use"),
#   ) -> None:
#       """Greet someone by name."""
#       typer.echo(f"{greeting}, {name}!")
#
# Generated output below:
# ─────────────────────────────────────────

"""FastAPI app generated by intpot."""

from fastapi import FastAPI
from pydantic import BaseModel, Field

app = FastAPI()




class AddRequest(BaseModel):
    a: int = Field(..., description="First number")
    b: int = Field(..., description="Second number")


@app.post("/add")
def add(request: AddRequest) -> dict:
    """Add two numbers together."""
    # TODO: implement
    return {"result": "add called"}



class GreetRequest(BaseModel):
    name: str = Field(..., description="Name to greet")
    greeting: str = Field(default='Hello', description="Greeting to use")


@app.post("/greet")
def greet(request: GreetRequest) -> dict:
    """Greet someone by name."""
    # TODO: implement
    return {"result": "greet called"}
