"""MCP server generated by intpot."""


from fastmcp import FastMCP as _intpot_mcp_fastmcp

mcp = _intpot_mcp_fastmcp('cli_app')
_intpot_required = object()


def _add_impl(
    a: int = _intpot_required,
    b: int = _intpot_required,
) -> str:
    """Add two numbers together."""
    if a is _intpot_required:
        raise TypeError('Missing required argument: a')
    if b is _intpot_required:
        raise TypeError('Missing required argument: b')
    return a + b


@mcp.tool(name='add')
def add(
    a: int,
    b: int,
) -> str:
    """Add two numbers together."""

    return _add_impl(a, b)

def _greet_impl(
    name: str = _intpot_required,
    greeting: str = 'Hello',
) -> str:
    """Greet someone by name."""
    if name is _intpot_required:
        raise TypeError('Missing required argument: name')
    return f'{greeting}, {name}!'


@mcp.tool(name='greet')
def greet(
    name: str,
    greeting: str = 'Hello',
) -> str:
    """Greet someone by name."""

    return _greet_impl(name, greeting)


if __name__ == "__main__":
    mcp.run()
