"""MCP server generated by intpot."""

from fastmcp import FastMCP

mcp = FastMCP("generated-server")



@mcp.tool()
def add(
    a: int,
    b: int,
) -> str:
    """Add two numbers together."""

    return a + b


@mcp.tool()
def greet(
    name: str,
    greeting: str = 'Hello',
) -> str:
    """Greet someone by name."""

    return f'{greeting}, {name}!'


if __name__ == "__main__":
    mcp.run()

