"""FastAPI app generated by intpot."""

from fastapi import FastAPI, Body

app = FastAPI()



@app.post("/add")
def add(
    a: int = Body(..., description="First number"),
    b: int = Body(..., description="Second number"),
) -> dict:
    """Add two numbers together."""

    return a + b


@app.post("/greet")
def greet(
    name: str = Body(..., description="Name to greet"),
    greeting: str = Body(default='Hello', description="Greeting to use"),
) -> dict:
    """Greet someone by name."""

    return f'{greeting}, {name}!'


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

