# Conversion: CLI (Typer) → MCP (FastMCP)
# Source:     ../cli_app.py
# Command:    intpot to mcp examples/cli_app.py
#
# Original input:
#
#   import typer
#   app = typer.Typer()
#
#   @app.command()
#   def add(
#       a: int = typer.Argument(..., help="First number"),
#       b: int = typer.Argument(..., help="Second number"),
#   ) -> None:
#       """Add two numbers together."""
#       typer.echo(a + b)
#
#   @app.command()
#   def greet(
#       name: str = typer.Argument(..., help="Name to greet"),
#       greeting: str = typer.Option("Hello", help="Greeting to use"),
#   ) -> None:
#       """Greet someone by name."""
#       typer.echo(f"{greeting}, {name}!")
#
# Generated output below:
# ─────────────────────────────────────────

"""MCP server generated by intpot."""

from fastmcp import FastMCP

mcp = FastMCP("generated-server")



@mcp.tool()
def add(
    a: int,
    b: int,
) -> str:
    """Add two numbers together."""
    # TODO: implement
    return "add called"


@mcp.tool()
def greet(
    name: str,
    greeting: str = 'Hello',
) -> str:
    """Greet someone by name."""
    # TODO: implement
    return "greet called"


if __name__ == "__main__":
    mcp.run()
