"""FastAPI app generated by intpot."""


from fastapi import FastAPI as _intpot_fastapi_FastAPI, Body as _intpot_fastapi_Body

app = _intpot_fastapi_FastAPI(title='cli_app')


@app.post("/add")
def add(
    a: int = _intpot_fastapi_Body(..., description='First number'),
    b: int = _intpot_fastapi_Body(..., description='Second number'),
) -> dict:
    """Add two numbers together."""

    return {'result': a + b}


@app.post("/greet")
def greet(
    name: str = _intpot_fastapi_Body(..., description='Name to greet'),
    greeting: str = _intpot_fastapi_Body(default='Hello', description='Greeting to use'),
) -> dict:
    """Greet someone by name."""

    return {'result': f'{greeting}, {name}!'}


if __name__ == "__main__":
    import uvicorn

    # Loopback only. Change to "0.0.0.0" to expose this on the network.
    uvicorn.run(app, host="127.0.0.1", port=8000)
