"""CLI app generated by intpot."""

import typer

app = typer.Typer()



@app.command()
def add(
    a: int = typer.Argument(..., help=""),
    b: int = typer.Argument(..., help=""),
) -> None:
    """Add two numbers together."""

    typer.echo(a + b)


@app.command()
def greet(
    name: str = typer.Argument(..., help=""),
    greeting: str = typer.Option('Hello', help=""),
) -> None:
    """Greet someone by name."""

    typer.echo(f'{greeting}, {name}!')


if __name__ == "__main__":
    app()

