"""CLI app generated by intpot."""

import typer

app = typer.Typer()


def _add_impl(
    a: int,
    b: int,
) -> None:
    """Add two numbers together."""
    typer.echo(a + b)


@app.command()
def add(
    a: int = typer.Argument(..., help=""),
    b: int = typer.Argument(..., help=""),
) -> None:
    """Add two numbers together."""
    result = _add_impl(a, b)
    if result is not None:
        typer.echo(result)


def _greet_impl(
    name: str,
    greeting: str,
) -> None:
    """Greet someone by name."""
    typer.echo(f'{greeting}, {name}!')


@app.command()
def greet(
    name: str = typer.Argument(..., help=""),
    greeting: str = typer.Option('Hello', help=""),
) -> None:
    """Greet someone by name."""
    result = _greet_impl(name, greeting)
    if result is not None:
        typer.echo(result)


if __name__ == "__main__":
    app()

