"""FastAPI app generated by intpot."""

from fastapi import FastAPI
from pydantic import BaseModel, Field

app = FastAPI()




class AddRequest(BaseModel):
    a: int = Field(..., description="")
    b: int = Field(..., description="")


@app.post("/add")
def add(request: AddRequest) -> dict:
    """Add two numbers together."""
    # TODO: implement
    return {"result": "add called"}



class GreetRequest(BaseModel):
    name: str = Field(..., description="")
    greeting: str = Field(default='Hello', description="")


@app.post("/greet")
def greet(request: GreetRequest) -> dict:
    """Greet someone by name."""
    # TODO: implement
    return {"result": "greet called"}

