# Conversion: MCP (FastMCP) → API (FastAPI)
# Source:     ../mcp_server.py
# Command:    intpot to api examples/mcp_server.py
#
# Original input:
#
#   from fastmcp import FastMCP
#   mcp = FastMCP("example-server")
#
#   @mcp.tool()
#   def add(a: int, b: int) -> int:
#       """Add two numbers together."""
#       return a + b
#
#   @mcp.tool()
#   def greet(name: str, greeting: str = "Hello") -> str:
#       """Greet someone by name."""
#       return f"{greeting}, {name}!"
#
# Generated output below:
# ─────────────────────────────────────────

"""FastAPI app generated by intpot."""

from fastapi import FastAPI
from pydantic import BaseModel, Field

app = FastAPI()




class AddRequest(BaseModel):
    a: int = Field(..., description="")
    b: int = Field(..., description="")


@app.post("/add")
def add(request: AddRequest) -> dict:
    """Add two numbers together."""
    # TODO: implement
    return {"result": "add called"}



class GreetRequest(BaseModel):
    name: str = Field(..., description="")
    greeting: str = Field(default='Hello', description="")


@app.post("/greet")
def greet(request: GreetRequest) -> dict:
    """Greet someone by name."""
    # TODO: implement
    return {"result": "greet called"}
